import { INestApplication } from '@nestjs/common';
import request from 'supertest';
import { App } from 'supertest/types';
import { PrismaService } from '../src/prisma/prisma.service';
import { createE2eApp, registerUser } from './support/test-app';

/**
 * Cascade-delete integration tests (plan.md Phase 1 "ต้องทำต่อ" → "ทดสอบ
 * cascade delete ของ user/session/message/artifact"). Verifies the actual
 * `ON DELETE` behavior declared in each migration's generated `migration.sql`
 * under `prisma/migrations/`, not just what `schema.prisma` says — confirmed
 * by reading the generated SQL directly:
 *
 *   users              -> chat_sessions        ON DELETE CASCADE
 *   users              -> refresh_tokens       ON DELETE CASCADE
 *   users              -> provider_credentials ON DELETE CASCADE
 *   chat_sessions      -> messages             ON DELETE CASCADE
 *   chat_sessions      -> code_artifacts       ON DELETE CASCADE (direct FK)
 *   messages           -> code_artifacts       ON DELETE CASCADE
 *   code_artifacts (parent_artifact_id, self)  ON DELETE SET NULL
 *
 * i.e. deleting a user cascades all the way down through sessions to
 * messages/artifacts; deleting a session (without deleting the user) also
 * cascades to its messages/artifacts; deleting one artifact revision does
 * *not* cascade-delete its child revisions, it only clears their
 * parentArtifactId (the revision chain is intentionally not a delete
 * cascade).
 */
describe('Cascade delete (e2e)', () => {
  let app: INestApplication<App>;
  let prisma: PrismaService;
  const createdUserIds: string[] = [];

  beforeAll(async () => {
    ({ app, prisma } = await createE2eApp());
  });

  afterEach(async () => {
    if (createdUserIds.length === 0) return;
    await prisma.user.deleteMany({
      where: { id: { in: createdUserIds.splice(0) } },
    });
  });

  afterAll(async () => {
    await app.close();
  });

  async function setUpFullChain(label: string) {
    const user = await registerUser(app, label);

    const created = await request(app.getHttpServer())
      .post('/api/chat/sessions')
      .set('Authorization', `Bearer ${user.accessToken}`)
      .send({ defaultProvider: 'ollama', defaultModel: 'test-model' })
      .expect(201);
    const session = created.body as { id: string };

    const message = await prisma.message.create({
      data: {
        sessionId: session.id,
        role: 'assistant',
        content: 'hello',
        streamingStatus: 'complete',
      },
    });

    const artifact = await prisma.codeArtifact.create({
      data: {
        sessionId: session.id,
        messageId: message.id,
        filename: 'src/cascade.ts',
        language: 'typescript',
        content: 'export const x = 1;',
        revision: 1,
        origin: 'ai',
      },
    });

    // The BYOK REST endpoint that used to write this row is gone (claude/openai are
    // now gated by the host-bridge, not a per-user key — see ProviderSettingsService),
    // but the `provider_credentials` table and its cascade-delete relation are
    // deliberately still in the schema (kept to avoid a migration, per plan.md Phase
    // 10), so this inserts the row directly to keep exercising that cascade.
    await prisma.providerCredential.create({
      data: {
        userId: user.user.id,
        provider: 'openai',
        encryptedApiKey: Buffer.from('cascade-test-secret'),
        encryptionVersion: 1,
      },
    });

    const refreshTokenCount = await prisma.refreshToken.count({
      where: { userId: user.user.id },
    });
    expect(refreshTokenCount).toBeGreaterThan(0);

    return { user, session, message, artifact };
  }

  it('cascades user deletion down to sessions, messages, artifacts, refresh tokens and provider credentials', async () => {
    const { user, session, message, artifact } = await setUpFullChain(
      'cascade-user-delete',
    );

    // uuidv7() format check (plan.md → "ตรวจ compatibility ของ uuidv7()"):
    // version nibble '7' and RFC 9562 variant bits, on every id generated by
    // Postgres's native uuidv7() default across every table in this chain.
    const uuidv7Pattern =
      /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
    expect(user.user.id).toMatch(uuidv7Pattern);
    expect(session.id).toMatch(uuidv7Pattern);
    expect(message.id).toMatch(uuidv7Pattern);
    expect(artifact.id).toMatch(uuidv7Pattern);

    // Deliberately not pushed to createdUserIds: this test deletes the user
    // itself as the thing under test, so afterEach's cleanup must not try to
    // delete it again.
    await prisma.user.delete({ where: { id: user.user.id } });

    await expect(
      prisma.chatSession.findUnique({ where: { id: session.id } }),
    ).resolves.toBeNull();
    await expect(
      prisma.message.findUnique({ where: { id: message.id } }),
    ).resolves.toBeNull();
    await expect(
      prisma.codeArtifact.findUnique({ where: { id: artifact.id } }),
    ).resolves.toBeNull();
    await expect(
      prisma.refreshToken.count({ where: { userId: user.user.id } }),
    ).resolves.toBe(0);
    await expect(
      prisma.providerCredential.count({ where: { userId: user.user.id } }),
    ).resolves.toBe(0);
  });

  it('cascades session deletion down to messages and artifacts without touching the owning user', async () => {
    const { user, session, message, artifact } = await setUpFullChain(
      'cascade-session-delete',
    );
    createdUserIds.push(user.user.id);

    await prisma.chatSession.delete({ where: { id: session.id } });

    await expect(
      prisma.message.findUnique({ where: { id: message.id } }),
    ).resolves.toBeNull();
    await expect(
      prisma.codeArtifact.findUnique({ where: { id: artifact.id } }),
    ).resolves.toBeNull();
    await expect(
      prisma.user.findUnique({ where: { id: user.user.id } }),
    ).resolves.not.toBeNull();
  });

  it('deleting one artifact revision clears (not cascades) its child revision link', async () => {
    const user = await registerUser(app, 'cascade-artifact-revision');
    createdUserIds.push(user.user.id);

    const created = await request(app.getHttpServer())
      .post('/api/chat/sessions')
      .set('Authorization', `Bearer ${user.accessToken}`)
      .send({ defaultProvider: 'ollama', defaultModel: 'test-model' })
      .expect(201);
    const session = created.body as { id: string };
    const message = await prisma.message.create({
      data: {
        sessionId: session.id,
        role: 'assistant',
        content: 'hello',
        streamingStatus: 'complete',
      },
    });

    const revision1 = await prisma.codeArtifact.create({
      data: {
        sessionId: session.id,
        messageId: message.id,
        filename: 'src/chain.ts',
        language: 'typescript',
        content: 'v1',
        revision: 1,
        origin: 'ai',
      },
    });
    const revision2 = await prisma.codeArtifact.create({
      data: {
        sessionId: session.id,
        messageId: message.id,
        filename: 'src/chain.ts',
        language: 'typescript',
        content: 'v2',
        revision: 2,
        parentArtifactId: revision1.id,
        origin: 'user',
      },
    });

    await prisma.codeArtifact.delete({ where: { id: revision1.id } });

    const survivingChild = await prisma.codeArtifact.findUnique({
      where: { id: revision2.id },
    });
    expect(survivingChild).not.toBeNull();
    expect(survivingChild?.parentArtifactId).toBeNull();
  });
});
